sudo: false

repos:
  CRAN: http://cran.rstudio.com/

language: r

cache:
  packages: true

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

matrix:
  include:
    - name: "R"
      r: 3.3.0
      warnings_are_errors: true
      script:
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud version
        - echo $TEST_GOOGLE_KEY_FILE > gcloud.b64
        - base64 --decode gcloud.b64 > gcloud.json
        - gcloud auth activate-service-account --key-file gcloud.json
        - |
          R CMD build --resave-data --no-build-vignettes .
          R CMD check --no-manual --ignore-vignettes --no-tests pins*tar.gz
          Rscript ci/travis.R
      env:
        -TEST_GITHUB_BRANCH="travis"
      after_success:
        - rm -rf ~/.pins
        - Rscript -e 'covr::codecov()'
  allow_failures:
    - name: "Python"
      r_packages:
        - feather
        - tibble
      before_install:
        - export LD_LIBRARY_PATH="/home/travis/R-bin/lib/R/lib:$LD_LIBRARY_PATH"
        - pip install pandas --user
        - pip install pytest --user
        - pip install feather-format --user
        - pip install -e python/. --user
      script:
        - R CMD build --no-build-vignettes .
        - Rscript -e 'install.packages(dir(".", pattern = "pins_"))'
        - pytest python/pins/tests/test.py
os:
  - linux
